services:
  mariadb:
  image: mariadb
  environment:
    - MARIADB_ROOT_PASSWORD=qh
    - MARIADB_USER=route
    - MARIADB_PASSWORD=root
    - MARIADB_DATABASE=meme-generator
    - MYSQL_DATABASE=${meme-generator}
  ports:
  - 3306:3306
  monapache:
    image: hugo38630/monapache
    ports:
      - 80:80
    environment:
      - SERVEUR_BD=${SERVEUR_BD}
  monubuntu:
    image: hugo38630/monubuntu
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
