services:
  mariadb:
  image: mariadb
  environment:
    - MARIADB_ROOT_PASSWORD=qh
    - MARIADB_USER=route
    - MARIADB_PASSWORD=root
    - MARIADB_DATEBASE=meme-generator
  ports:
  - 3306:3306
  monapache:
    image: hugo38630/monapache
    ports:
      - 80:80
  monubuntu:
    image: hugo38630/monubuntu
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
